### ISSUE TITLE
ChIPKernels fails to compile in R 4.5 because of change in names of R API macros

### ISSUE THREAD

**Issue by afayyazuddin** [ManuSetty/ChIPKernels#1]
The error is in compilation of hamming.c due to removal of the macros Calloc, Free, and Realloc from the R API (https://stat.ethz.ch/R-manual/R-devel/doc/manual/R-exts.html). The new macros are now called R_Calloc, R_Free, and R_Realloc and the code compiles when the old names are replaced with the new ones.
A screenshot of the compilation error is shown below:

<img width="1081" height="344" alt="Image" src="https://github.com/user-attachments/assets/ecb7ecc2-b0a4-4bbf-b2f7-d59c3bdc8c19" />
